/*
SPACE COMPLEXITY:
          ORDER OF GROWTH OF MEMORY SPACE IN TERMS OF INPUT SIZE

INT SUM(INT N)
{
    RETURN N*(N+1)/2
}          


 THETA(1) OR BIG-OH(1)  -  AS ONLY CONSTANT ORDER OF GROWTH IS REQUIRED
*/